### ISSUE TITLE
Slurm 22.05 support (cpus-per-task)

### ISSUE THREAD

**Issue by JanVogelsang** [INM-6/beNNch#62]
Slurm 22.05 has just been introduced to the JSC clusters with the following changes:

>   - srun will no longer read in SLURM_CPUS_PER_TASK and will not inherit option
>     --cpus-per-task from sbatch! This means you will explicitly have to specify
>     --cpus-per-task to your srun calls, or set the new SRUN_CPUS_PER_TASK env
>     var. If you want to keep using --cpus-per-task with sbatch then you will
>     have to add: "export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}".
>   - Using the option --cpus-per-task in 22.05 does imply --exact, which
>     means that each step with --cpus-per-task will now only get the minimum
>     number of cores. The pinning will change (implication on the performance)
>     and the tasks will fill the HW threads of same cores. If you don’t use SMT
>     and want to keep old behavior as before where your threads run only on
>     real cores then add this to srun: "--threads-per-core=1".

We are currently implementing the `--cpus-per-task` setting via the `threads_per_task` configuration option. BeNNch might now have to be adapted to the new Slurm version.

**Comment by jhnnsnk** [comment]
Solved by #63
